theme: jekyll-theme-minimal
title: Welcome to the Ceyda’s homepage!
description: Feel free to bookmark this to keep an eye on my project updates
- name: Deploy to GitHub Pages
  uses: JamesIves/github-pages-deploy-action@4.0.0

